# Generated by Django 5.1.4 on 2025-04-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
