# Generated by Django 5.1.4 on 2025-04-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_profile_picture_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
