# Generated by Django 5.1.4 on 2025-04-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='profile_picture',
            new_name='image',
        ),
    ]
